
Global weapon_data_csv_field_order_template:TList = CreateList()
weapon_data_csv_field_order_template.AddLast( "name" )
weapon_data_csv_field_order_template.AddLast( "id" )
weapon_data_csv_field_order_template.AddLast( "rarity" )
weapon_data_csv_field_order_template.AddLast( "base_value" )
weapon_data_csv_field_order_template.AddLast( "range" )
weapon_data_csv_field_order_template.AddLast( "damage/second" )
weapon_data_csv_field_order_template.AddLast( "damage/shot" )
weapon_data_csv_field_order_template.AddLast( "emp" )
weapon_data_csv_field_order_template.AddLast( "impact" )
weapon_data_csv_field_order_template.AddLast( "turn rate" )
weapon_data_csv_field_order_template.AddLast( "OPs" )
weapon_data_csv_field_order_template.AddLast( "ammo" )
weapon_data_csv_field_order_template.AddLast( "ammo/sec" )
weapon_data_csv_field_order_template.AddLast( "reload size" )
weapon_data_csv_field_order_template.AddLast( "type" )
weapon_data_csv_field_order_template.AddLast( "energy/shot" )
weapon_data_csv_field_order_template.AddLast( "energy/second" )
weapon_data_csv_field_order_template.AddLast( "chargeup" )
weapon_data_csv_field_order_template.AddLast( "chargedown" )
weapon_data_csv_field_order_template.AddLast( "burst size" )
weapon_data_csv_field_order_template.AddLast( "burst delay" )
weapon_data_csv_field_order_template.AddLast( "min spread" )
weapon_data_csv_field_order_template.AddLast( "max spread" )
weapon_data_csv_field_order_template.AddLast( "spread/shot" )
weapon_data_csv_field_order_template.AddLast( "spread decay/sec" )
weapon_data_csv_field_order_template.AddLast( "beam speed" )
weapon_data_csv_field_order_template.AddLast( "proj speed" )
weapon_data_csv_field_order_template.AddLast( "launch speed" )
weapon_data_csv_field_order_template.AddLast( "flight time" )
weapon_data_csv_field_order_template.AddLast( "proj hitpoints" )
weapon_data_csv_field_order_template.AddLast( "hints" )
weapon_data_csv_field_order_template.AddLast( "tags" )
weapon_data_csv_field_order_template.AddLast( "number" )

Global weapon_data_csv_field_template:TMap = CreateMap()
weapon_data_csv_field_template.Insert( "name", "weapon CSV name" )
weapon_data_csv_field_template.Insert( "id", "new_weapon" )
weapon_data_csv_field_template.Insert( "rarity", Null )
weapon_data_csv_field_template.Insert( "base_value", Null )
weapon_data_csv_field_template.Insert( "range", Null )
weapon_data_csv_field_template.Insert( "damage/second", Null )
weapon_data_csv_field_template.Insert( "damage/shot", Null )
weapon_data_csv_field_template.Insert( "emp", Null )
weapon_data_csv_field_template.Insert( "impact", Null )
weapon_data_csv_field_template.Insert( "turn rate", Null )
weapon_data_csv_field_template.Insert( "OPs", Null )
weapon_data_csv_field_template.Insert( "ammo", Null )
weapon_data_csv_field_template.Insert( "ammo/sec", Null )
weapon_data_csv_field_template.Insert( "reload size", Null )
weapon_data_csv_field_template.Insert( "type", "KINETIC" )
weapon_data_csv_field_template.Insert( "energy/shot", Null )
weapon_data_csv_field_template.Insert( "energy/second", Null )
weapon_data_csv_field_template.Insert( "chargeup", Null )
weapon_data_csv_field_template.Insert( "chargedown", Null )
weapon_data_csv_field_template.Insert( "burst size", Null )
weapon_data_csv_field_template.Insert( "burst delay", Null )
weapon_data_csv_field_template.Insert( "min spread", Null )
weapon_data_csv_field_template.Insert( "max spread", Null )
weapon_data_csv_field_template.Insert( "spread/shot", Null )
weapon_data_csv_field_template.Insert( "spread decay/sec", Null )
weapon_data_csv_field_template.Insert( "beam speed", Null )
weapon_data_csv_field_template.Insert( "proj speed", Null )
weapon_data_csv_field_template.Insert( "launch speed", Null )
weapon_data_csv_field_template.Insert( "flight time", Null )
weapon_data_csv_field_template.Insert( "proj hitpoints", Null )
weapon_data_csv_field_template.Insert( "hints", Null )
weapon_data_csv_field_template.Insert( "tags", Null )
weapon_data_csv_field_template.Insert( "number", Null )


