
Global wing_data_csv_field_order_template:TList = CreateList()
wing_data_csv_field_order_template.AddLast( "id" )
wing_data_csv_field_order_template.AddLast( "variant" )
wing_data_csv_field_order_template.AddLast( "fleet pts" )
wing_data_csv_field_order_template.AddLast( "hyperdrive" )
wing_data_csv_field_order_template.AddLast( "formation" )
wing_data_csv_field_order_template.AddLast( "num" )
wing_data_csv_field_order_template.AddLast( "role" )
wing_data_csv_field_order_template.AddLast( "refit" )
wing_data_csv_field_order_template.AddLast( "base value" )

Global wing_data_csv_field_template:TMap = CreateMap()
wing_data_csv_field_template.Insert( "id", "new_wing_id" )
wing_data_csv_field_template.Insert( "variant", "variant_id" )
wing_data_csv_field_template.Insert( "fleet pts", "3" )
wing_data_csv_field_template.Insert( "hyperdrive", "" )
wing_data_csv_field_template.Insert( "formation", "V" )
wing_data_csv_field_template.Insert( "num", "3" )
wing_data_csv_field_template.Insert( "role", "FIGHTER" )
wing_data_csv_field_template.Insert( "refit", "5" )
wing_data_csv_field_template.Insert( "base value", "2000" )
