
Global wing_data_csv_field_order_template:TList = CreateList()
wing_data_csv_field_order_template.AddLast( "id" )
wing_data_csv_field_order_template.AddLast( "variant" )
wing_data_csv_field_order_template.AddLast( "tags" )
wing_data_csv_field_order_template.AddLast( "tier" )
wing_data_csv_field_order_template.AddLast( "rarity" )
wing_data_csv_field_order_template.AddLast( "fleet pts" )
wing_data_csv_field_order_template.AddLast( "op cost" )
wing_data_csv_field_order_template.AddLast( "formation" )
wing_data_csv_field_order_template.AddLast( "range" )
wing_data_csv_field_order_template.AddLast( "attackRunRange" )
wing_data_csv_field_order_template.AddLast( "num" )
wing_data_csv_field_order_template.AddLast( "role" )
wing_data_csv_field_order_template.AddLast( "role desc" )
wing_data_csv_field_order_template.AddLast( "refit" )
wing_data_csv_field_order_template.AddLast( "base value" )
wing_data_csv_field_order_template.AddLast( "number" )

Global wing_data_csv_field_template:TMap = CreateMap()
wing_data_csv_field_template.Insert( "id", "new_hull_variant_wing" )
wing_data_csv_field_template.Insert( "variant", "new_hull_variant" )
wing_data_csv_field_template.Insert( "tags", Null )
wing_data_csv_field_template.Insert( "tier", "0" )
wing_data_csv_field_template.Insert( "rarity", Null )
wing_data_csv_field_template.Insert( "fleet pts", "0" )
wing_data_csv_field_template.Insert( "op cost", "0" )
wing_data_csv_field_template.Insert( "formation", "V" )
wing_data_csv_field_template.Insert( "range", "4000" )
wing_data_csv_field_template.Insert( "attackRunRange", "500" )
wing_data_csv_field_template.Insert( "num", "1" )
wing_data_csv_field_template.Insert( "role", "FIGHTER" )
wing_data_csv_field_template.Insert( "role desc", "Fighter" )
wing_data_csv_field_template.Insert( "refit", "10" )
wing_data_csv_field_template.Insert( "base value", "2000" )
wing_data_csv_field_template.Insert( "number", Null )
